apiVersion: platform.kratix.io/v1alpha1
kind: GitStateStore
metadata:
  name: my-git-store
spec:
  url: https://github.com/mazsola2k/kratix.git
  branch: main
  directory: state
  gitAuthor:
    name: kratix
  secretRef:
    name: git-credentials
    namespace: kratix-platform-system